export const ITEM_POOL = [
  { id: 0, name: "Espada de Fuego", durability: 84, quality: 4 , sprite:'/fire_sword.png'},
{ id: 1, name: "Escudo de Hierro", durability: 72, quality: 3 , sprite:'../../public/fire_sword.png'},
{ id: 2, name: "Arco Élfico", durability: 59, quality: 5 , sprite:'../../public/elf_bow.png'},
{ id: 3, name: "Capa de Invisibilidad", durability: 66, quality: 2 , sprite:'../../public/fire_sword.png'},
{ id: 4, name: "Amuleto del Sabio", durability: 91, quality: 5 , sprite:'../../public/fire_sword.png'},
{ id: 5, name: "Botas del Viento", durability: 38, quality: 3 , sprite:'../../public/fire_sword.png'},
{ id: 6, name: "Hacha del Trueno", durability: 75, quality: 4 , sprite:'../../public/fire_sword.png'},
{ id: 7, name: "Daga de Sombras", durability: 47, quality: 2 , sprite:'../../public/fire_sword.png'},
{ id: 8, name: "Báculo de Hielo", durability: 53, quality: 5 , sprite:'../../public/fire_sword.png'},
{ id: 9, name: "Casco del Guerrero", durability: 64, quality: 3 , sprite:'../../public/fire_sword.png'},
{ id: 10, name: "Guantes de Poder", durability: 82, quality: 4 , sprite:'../../public/fire_sword.png'},
{ id: 11, name: "Anillo del Caos", durability: 29, quality: 1 , sprite:'../../public/fire_sword.png'},
{ id: 12, name: "Lanza Sagrada", durability: 77, quality: 5 , sprite:'../../public/fire_sword.png'},
{ id: 13, name: "Ballesta Envenenada", durability: 46, quality: 2 , sprite:'../../public/fire_sword.png'},
{ id: 14, name: "Túnica Arcana", durability: 88, quality: 4 , sprite:'../../public/fire_sword.png'},
{ id: 15, name: "Collar del Lobo", durability: 35, quality: 3 , sprite:'../../public/fire_sword.png'},
{ id: 16, name: "Martillo del Destino", durability: 93, quality: 5, sprite:'../../public/fire_sword.png' },
{ id: 17, name: "Grebas de Acero", durability: 71, quality: 4 },
{ id: 18, name: "Cinturón del Gigante", durability: 58, quality: 3 },
{ id: 19, name: "Orbe del Vacío", durability: 26, quality: 2 },
{ id: 20, name: "Libro de Hechizos", durability: 44, quality: 4 },
{ id: 21, name: "Yelmo Maldito", durability: 19, quality: 1 },
{ id: 22, name: "Espada Rúnica", durability: 68, quality: 4 },
{ id: 23, name: "Escudo Solar", durability: 95, quality: 5 },
{ id: 24, name: "Guadaña Oscura", durability: 41, quality: 2 }]