export const ITEM_POOL = [
  { id: 0, name: "Espada de Fuego", durability: 84, quality: 4, sprite: '/fire_sword.png', description: "Una espada envuelta en llamas eternas, capaz de incendiar a sus enemigos." },
  { id: 1, name: "Escudo de Hierro", durability: 72, quality: 3, sprite: '../../public/fire_sword.png', description: "Un escudo robusto forjado en hierro puro, ideal para resistir embestidas brutales." },
  { id: 2, name: "Arco Élfico", durability: 59, quality: 5, sprite: '../../public/elf_bow.png', description: "Un arco ligero y preciso, creado por artesanos élficos para cazadores expertos." },
  { id: 3, name: "Capa de Invisibilidad", durability: 66, quality: 2, sprite: '../../public/fire_sword.png', description: "Una capa encantada que permite al portador desvanecerse de la vista." },
  { id: 4, name: "Amuleto del Sabio", durability: 91, quality: 5, sprite: '../../public/fire_sword.png', description: "Un amuleto antiguo que otorga sabiduría y visión más allá del tiempo." },
  { id: 5, name: "Botas del Viento", durability: 38, quality: 3, sprite: '../../public/fire_sword.png', description: "Estas botas mágicas permiten correr más rápido que cualquier tormenta." },
  { id: 6, name: "Hacha del Trueno", durability: 75, quality: 4, sprite: '../../public/fire_sword.png', description: "Un hacha imbbuida con el poder del trueno, capaz de partir montañas." },
  { id: 7, name: "Daga de Sombras", durability: 47, quality: 2, sprite: '../../public/fire_sword.png', description: "Una daga furtiva que se esconde entre las sombras para atacar sin ser vista." },
  { id: 8, name: "Báculo de Hielo", durability: 53, quality: 5, sprite: '../../public/fire_sword.png', description: "Un báculo encantado que canaliza el frío del invierno eterno." },
  { id: 9, name: "Casco del Guerrero", durability: 64, quality: 3, sprite: '../../public/fire_sword.png', description: "Un casco resistente usado por los guerreros más valientes del reino." },
  { id: 10, name: "Guantes de Poder", durability: 82, quality: 4, sprite: '../../public/fire_sword.png', description: "Guantes reforzados que otorgan una fuerza descomunal al portador." },
  { id: 11, name: "Anillo del Caos", durability: 29, quality: 1, sprite: '../../public/fire_sword.png', description: "Un anillo prohibido que trae inestabilidad y destrucción a quien lo use." },
  { id: 12, name: "Lanza Sagrada", durability: 77, quality: 5, sprite: '../../public/fire_sword.png', description: "Una lanza bendecida por los dioses, mortal contra las criaturas oscuras." },
  { id: 13, name: "Ballesta Envenenada", durability: 46, quality: 2, sprite: '../../public/fire_sword.png', description: "Una ballesta cuyas flechas están impregnadas de veneno letal." },
  { id: 14, name: "Túnica Arcana", durability: 88, quality: 4, sprite: '../../public/fire_sword.png', description: "Una túnica tejida con hilos mágicos que amplifican el poder de los hechizos." },
  { id: 15, name: "Collar del Lobo", durability: 35, quality: 3, sprite: '../../public/fire_sword.png', description: "Un collar rúnico que otorga la ferocidad y el instinto de un lobo salvaje." },
  { id: 16, name: "Martillo del Destino", durability: 93, quality: 5, sprite: '../../public/fire_sword.png', description: "Un martillo titánico que decide el destino de quienes recibe su golpe." },
  { id: 17, name: "Grebas de Acero", durability: 71, quality: 4, description: "Protecciones de acero reforzado que garantizan una defensa firme en batalla." },
  { id: 18, name: "Cinturón del Gigante", durability: 58, quality: 3, description: "Un cinturón mágico que otorga la fuerza descomunal de un gigante." },
  { id: 19, name: "Orbe del Vacío", durability: 26, quality: 2, description: "Un orbe oscuro que absorbe la luz y drena la energía vital de su entorno." },
  { id: 20, name: "Libro de Hechizos", durability: 44, quality: 4, description: "Un grimorio repleto de conjuros antiguos y secretos olvidados." },
  { id: 21, name: "Yelmo Maldito", durability: 19, quality: 1, description: "Un yelmo maldito que ofrece poder a cambio de la cordura del portador." },
  { id: 22, name: "Espada Rúnica", durability: 68, quality: 4, description: "Una espada grabada con runas antiguas que incrementan su poder místico." },
  { id: 23, name: "Escudo Solar", durability: 95, quality: 5, description: "Un escudo brillante que refleja la luz solar para cegar a los enemigos." },
  { id: 24, name: "Guadaña Oscura", durability: 41, quality: 2, description: "Una guadaña siniestra utilizada por heraldos de la muerte." }
];
